spring:
  application:
    name: agent

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

anthropic:
  api-key: ${ANTHROPIC_API_KEY:missing-key}
  model-name: claude-3-5-sonnet-20241022

mcp:
  server-url: http://localhost:8081/mcp/chat


